### ISSUE TITLE
Ship ES5 npm package

### ISSUE THREAD

**Issue by jdetle** [bcoin-org/bsock#1]
Hi, I want to use bclient in a react app, in order to do so I need es5 npm packages: https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by bucko13** [comment]
[bPanel](https://bpanel.org) is a React project that uses bcurl and bsock without any problem. You can take a look at the project repo on GitHub to see how the webpack configs are setup and see if that helps: https://github.com/bpanel-org/bpanel

**Comment by chjj** [comment]
ES5 modules are still considered experimental in node.js. I don't think we should switch to the new module system until there is stable support. Closing.

**Comment by jdetle** [comment]
@chjj What I meant to say was that there was experimental javascript ES6 javascript syntax. CRA V2 supports compilation of node_modules, so I guess the point is moot.
